### ISSUE TITLE
Overall V2 Migration

### ISSUE THREAD

**Issue by TheLDB** [TheLDB/farcaster-rs#10]
How do we want to split up/manage migration from V1 -> V2 endpoints & authentication? open to any ideas, just excited to be able to build out fc-rs and add fulll features :D 

cc @MistApproach

**Comment by TheLDB** [comment]
also: should we work off of a v2 branch or just keep pushing to main?

**Comment by MistApproach** [comment]
Just proposed creating a separate branch precisely for that _before_ seeing this thread 😃 
Go ahead!

As for the more general thoughts on migration: when working on code i constantly get the feeling we need higher level abstractions (structs/traits). Don't have a clear picture of this yet. 
Since you already wrote some auth code could you implement this on a v2 branch?
Possibly create a separate struct under Farcaster (FarcasterAuth?) and implement all the required auth steps as separate functions (generating bearing token, requesting token etc.) ?

**Comment by TheLDB** [comment]
for sure, ill create a v2-api branch later today and start working on some (rough) code for that, testing endpoints & real auth will be rough since the APIs arent live, but having it there will be nice

pushing 28hrs of no sleep so dont quite trust myself to write it rn
