### ISSUE TITLE
PRs without creating branches?

### ISSUE THREAD

**Issue by MistApproach** [TheLDB/farcaster-rs#6]
From my experience it slows down work considerably as i switch from one task to another. Besides my local repo is a mess.
Could we possibly accept PRs in a more traditional way?

**Comment by TheLDB** [comment]
yeah im 100% open to that

whats your suggestion?

**Comment by MistApproach** [comment]
If you ask me i would keep it as simple as we can for now :)
I'm no expert by any means but allow me to share some more thoughts and ideas:

1. We're faaaaaaaaaaaaaaaaaaaaaaar from any kind of API stabilization
2. Farcaster protocol on it's own is heavily evolving and many things WILL change
3. With regards to above i think we should focus on getting basic things right and start building whatever we think may prove useful in the long run
4. Lets stick to one branch and accept PRs without requiring additional branching (being early we can always revert!)
5. More branches can be added as we see fit, but lets branch only when necessary/comfortable (projects with hundreds of branches are very cumbersome to explore)
7. Lets stick to symantic versioning https://semver.org so a) anything can change below 1.0.0 b) stick to 0.1.0 for now and increase minor/patch version as needed (we don't have to do it often)
8. I would get rid of extra documentation for now and stick to doc-comments. It becomes a nightmare to update anything except doc-comments with API not stable. We can rm doc for now and bring it back when farcaster-rs becomes usable (so your work is not lost)
9. Lets format code with rustfmt before pushing

Do you use farcaster client with DC support?

**Comment by TheLDB** [comment]
re 1-3: heavily agree, what kind of things do you think this includes? i want to add posting & auth support but until the jwt method changes (which it seemingly will) thats a very hard task due to how they sign their jwts

re 4-5: sounds good to me

re 6: sounds good to me. ill bump to 0.1.0 tn

re 7: makes sense, lets do it

re 8: yeah that sounds good to me as well

I don't use DC very much, they just seem fairly unstable right now compared to the alternatives (telegram, twitter dms, etc...) since they can fail at random & disappear after a while

**Comment by TheLDB** [comment]
update: merged, bumped to 0.1.0 standard, publishing now

@MistApproach thoughts on using https://github.com/rhysd/cargo-husky to add a cargo-fmt pre-push hook? 

we could also avoid writing tests for now since we will probably have to rewrite them multiple times with breaking changes in major ways, but add tests to pre-push eventually

**Comment by MistApproach** [comment]
Thanks, never used husky myself but it sounds like a good idea - i find myself forgetting about fmt before pushing sometimes

As for the tests i totally agree
